import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_component/header/page";
import Footer from "./_component/footer/page";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="js fnx-site chrome chrome-134 no-touchevents is-loaded">
      <head>
        <link rel='stylesheet' href='/assets/stylesheet/main.min.css' media='all' />
        {/* <link rel='stylesheet' href='/assets/stylesheet/style.css' media='all' /> */}
      </head>
      <body
        id="htmlBody" data-ga-page-subtype=""
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
